### PR TITLE
align_swe_merge_orchestrator_with_real_world_conditions

### PR DESCRIPTION
**Pull request by FranckLecuyer**
**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

### CODE REVIEW

**Comment by SlimaneAmar** [comment]
Should we not rename EntsoeCaseInfos by UcteCaseInfos ?

**Comment by SlimaneAmar** [comment]
It looks a little confused to me.
The notion of tso seems to be the same as geographicalCode in the code.

**Comment by SlimaneAmar** [comment]
What is the value of buisinessProcess for ID cgmes ?

**Comment by FranckLecuyer** [comment]
> What is the value of buisinessProcess for ID cgmes ?

businessProcess (String: YR, MO, WK, 2D, 1D, 23, …, 01 or RT)

**Review by SlimaneAmar — APPROVED** [review]

**Review by jonenst — APPROVED** [review]

**Pull request merged**
